# -*- coding: utf-8 -*-
"""GenAi_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlYbQtl5DKMLeCwIM1PXGtWq1iKJpzv3
"""

import numpy as np
print("----Simple Attention Mech Explanation")
encoder_outputs = np.array([
    [0.1,0.2],
    [0.5,0.3],
    [0.2,0.8],
    [0.9,0.1]
])
print(f"\nEncoder Outputs(4 words , 2 features each):\n{encoder_outputs}")
decoder_hidden_state=np.array([0.7,0.4])
print(f"\nDecoder Hidden state (what we mare looking):{decoder_hidden_state}")
alignment_scores=np.dot(encoder_outputs,decoder_hidden_state)
print(f"\nAlignment Scores (similiarity of each encoder output to decoder state):{alignment_scores}")
def softmax(x):
  e_x=np.exp(x-np.max(x))
  return e_x/e_x.sum(axis=0)
attention_weights=softmax(alignment_scores)
print(f"\n Attention Weights (how much to 'pay attention' to each word):{attention_weights}")
print(f"(Notice that the word 'student' (index 3) got a higher weight, meaning its more relevant to learning )")
context_vector=np.sum(encoder_outputs*attention_weights[:,np.newaxis],axis=0)
print(f"\n Context Vector (Weighted ssum of encoder outputs,'paying attention'):{context_vector}")