# -*- coding: utf-8 -*-
"""GenAi_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYxrMKriVeblOAHCb2PwPkqrjT0zZ6sI
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense

# Sample training corpus
text = """
deep learning is powerful
deep learning is useful
machine learning is interesting
neural networks are powerful
neural networks are useful
"""

# Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

total_words = len(tokenizer.word_index) + 1

# Convert text to sequences
sequences = []
for line in text.strip().split("\n"):
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        sequences.append(token_list[:i + 1])

# Padding
max_sequence_len = max(len(seq) for seq in sequences)
sequences = np.array(
    pad_sequences(sequences, maxlen=max_sequence_len, padding="pre")
)

# Input and target
X = sequences[:, :-1]
y = sequences[:, -1]

# One-hot encode target
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

rnn_model = Sequential([
    Embedding(total_words, 64, input_length=max_sequence_len - 1),
    SimpleRNN(128),
    Dense(total_words, activation="softmax")
])

rnn_model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

rnn_model.fit(X, y, epochs=100, verbose=1)