# -*- coding: utf-8 -*-
"""GenAi_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq_pQoqTmEJzbcQ1RYnyuN97cD5SFeJY
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense

X = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [4, 5, 6, 7],
    [5, 6, 7, 8],
    [6, 7, 8, 9]
])

Y = np.array([
    [4, 3, 2, 1],
    [5, 4, 3, 2],
    [6, 5, 4, 3],
    [7, 6, 5, 4],
    [8, 7, 6, 5],
    [9, 8, 7, 6]
])

X = X.reshape((X.shape[0], X.shape[1], 1))
Y = Y.reshape((Y.shape[0], Y.shape[1], 1))

encoder_inputs = Input(shape=(4, 1))

encoder_lstm = LSTM(64, return_state=True)

encoder_output, state_h, state_c = encoder_lstm(encoder_inputs)

encoder_states = [state_h, state_c]

decoder_inputs = Input(shape=(4, 1))

decoder_lstm = LSTM(
    64,
    return_sequences=True,
    return_state=True
)

decoder_output, _, _ = decoder_lstm(
    decoder_inputs,
    initial_state=encoder_states
)

decoder_dense = Dense(1)

decoder_output = decoder_dense(decoder_output)

model = Model(
    [encoder_inputs, decoder_inputs],
    decoder_output
)

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

decoder_X = X

model.fit(
    [X, decoder_X],
    Y,
    epochs=500,
    verbose=0
)

print("Model training completed!")

test_input = np.array([[7, 8, 9, 10]])

test_input = test_input.reshape((1, 4, 1))

prediction = model.predict(
    [test_input, test_input],
    verbose=0
)

print("Input Sequence:")
print(test_input.flatten())

print("Predicted Output:")
print(np.round(prediction.flatten(), 2))

print("Expected Output:")
print([10, 9, 8, 7])